name: p2e2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - plotly
  - pytorch
  - torchvision
  - tqdm
  - numpy
  - python=3.8
  - mkl
  - pip:
    - gym
    - opencv-python
    - tensorboardx
    - pyopengl
    - pyglet==1.5.11

