name: p2e2
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - plotly
  - pytorch
  - cudatoolkit=10.2
  - torchvision
  - tqdm
  # - numpy
  - setuptools
  - pip
  - python=3.8
  - mkl
  - pip:
    - colorama # needed for tqdm on windows
    - numpy
    - gym
    - opencv-python
    - tensorboardx
    - pyopengl
    - pyglet==1.5.11

